services:
  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend/Interface:/usr/share/nginx/html

  backend:
    build: ./backend
    ports:
      - "8025:8025"