/* autogenerated by Processing revision 1307 on 2026-03-26 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import websockets.*;
import processing.serial.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class serveurJava extends PApplet {

Communications com;
PApplet pApplet;
int nMoteurs = 10;
CaseMot [] casesMot;
boolean on = false;


public void setup() {
  /* size commented out by preprocessor */;
  fill(255);
  stroke(255);
  textSize(16);

  casesMot = new CaseMot[nMoteurs];
  for (int i = 0; i<nMoteurs; i++) {
    casesMot[i] = new CaseMot(i);
  }

  pApplet = this;

  com = new Communications(pApplet);

  com.start();

}

public void draw() {
  background(0);
  fill(255);
  for (int i = 0; i<nMoteurs; i++) {
      casesMot[i].maj();
    }
}

public void mouseWheel(MouseEvent event) {
  float e = event.getCount();
  for (int i = 0; i<nMoteurs; i++) {
    casesMot[i].incVitesse(PApplet.parseInt(-e));
  }
}

public void webSocketServerEvent(String msg) {
  com.setWsRecu(msg);
  println("recu du websocket client = \t" + msg);
  
}
class CaseMot {
  private int xAff, yAff;
  private int l,h;
  private boolean sel = false;
  private int id = 0;
  private String textPos = "pos = 0";
  private String textVit = "vit = 0";
  private byte vitesse;
  
  CaseMot(int _id){
    vitesse = 0;
    id = _id;
    l = width/(nMoteurs/2);
    h = height/4;
    xAff = (id%(nMoteurs/2))*l;
    yAff = floor(id/(nMoteurs/2))*h+height/2;
  }
  
  public void maj(){
    aff();
  }
  
  public void aff(){
    if(isSel()) fill(0,180,0);
    else if (mouseOver()) fill(100);
    else fill(0);
    
    rect(xAff,yAff,l,h);
    fill(255);
    text(id,xAff+10,yAff+20);
    textPos = "pos = " + com.getPos()[id];
    text(textPos,xAff+10,yAff+40);
    text(textVit,xAff+10,yAff+60);

  }
  
  public boolean mouseOver(){
    if(mouseX>xAff && mouseX<xAff+l && mouseY>yAff && mouseY<yAff+h) return true;
    else return false;
  }
  
  public boolean isSel(){
    if(mousePressed && (mouseButton == LEFT) && mouseOver()){
      for(int i=0;i<nMoteurs;i++){
        if (i != id) casesMot[i].sel = false;
      }
      sel = true;
    }
    return sel;
  }
  
  public void incVitesse(int e){
    if(sel) vitesse +=e;
    if(vitesse>127) vitesse = 127;
    if(vitesse<-127) vitesse = -127;
    textVit = "vit = " + vitesse;
    
  }
  
  public byte getVitesse(){
    return vitesse;
    //print(vitesse + " ; ");
  }

  public void setVitesse(int _v){
    vitesse = PApplet.parseByte(_v);
    textVit = "vit = " + vitesse;
  }

}


public class Communications extends Thread {
  Motif motif;
  int[] positions;
  byte[] vitesses;
  long maintenant, to;
  byte in = 6;
  
  Serial myPort ;
  WebsocketServer ws;
  String ModeRecu = "";
  String MotifRecu = "";


  Communications(PApplet _pApplet) {
    pApplet = _pApplet;
    motif = new Motif();
    positions = new int[nMoteurs];
    vitesses = new byte [nMoteurs];
    ws = new WebsocketServer(pApplet, 8025, "/mobile");
    to=System.nanoTime();
  }

  public void start() {
    super.start();
  }

  public void run() {
    while (true) {
      maintenant = System.nanoTime();
      int dt = 73530*256;
      if ((maintenant - to)>dt) { // permet de simuler le comportement d'Arduino ...
        if (in == 6) {
          motif.maj(positions);
          calcVitesses();
          calcPos();
          String msg="POS,";
          for (int i = 0; i<nMoteurs; i++) {
            msg +=positions[i] + ",";
          }
          msg+="FIN";
          ws.sendMessage(msg);
        } else {
          print(hex(in) + " ");
        }
        to = to + dt;
      } else delay(1); 
    }
  }


  public void calcVitesses() {
    motif.maj(positions);
    vitesses = motif.getVitesse();
  }

  public void calcPos() {
    for (int i =0; i<nMoteurs; i++) {
      positions[i] += vitesses[i];
    }
  }

  

  public byte[] getVitesses() {
    return vitesses;
  }

  public int[] getPos() {
    return positions;
  }

  public void setWsRecu(String _s) {
    if (_s.equals("on")) on = true;
    else if (_s.equals("off")) on = false;
    else if (_s.equals("raz")) {
      for (int i=0; i<nMoteurs; i++) {
        casesMot[i].sel = false;
        casesMot[i].setVitesse(0);
        motif.raz();
        positions[i] = 0;
        vitesses[i] = 0;
      }
    } else if (_s.substring(0, 4).equals("vmot")) {
      int idMot = PApplet.parseInt(_s.substring(4, 7));
      println("Moteur= "+idMot);
      int vMot = PApplet.parseInt(_s.substring(8, _s.length()));
      println("Vitesse= "+vMot);
      casesMot[idMot].sel = true;
      casesMot[idMot].setVitesse(vMot);
      
    } else if (_s.substring(0, 6).equals("motif=")) {
      MotifRecu = _s.substring(6, _s.length());
      println("nouveau motif = " + MotifRecu);
    } else if (_s.substring(0, 5).equals("mode=")) {
      ModeRecu = _s.substring(5, _s.length());
      //TO DO
      println("nouveau mode = " + ModeRecu);
    } else println("message ws recu inconnu = " + _s);
  }

  public void resetPos() {
    for (int i =0; i<nMoteurs; i++) {
      positions[i] = 0;
    }
  }
 
  
  
  
  
  /*void serialEvent(Serial p) 
{ 
  byte in = byte(p.readChar());
  if (in == 6)
  {
    for (int i=0; i<nMoteurs; i++)
    {
      myPort.write(vitesses[i]);
      calcPos();
      motif.maj(positions);
    }
    myPort.write(0x80);
    //myPort.write(vitesse[0]);
  } else
  {
    println(hex(in));
  }
}

void connexionSerie()
{
  try // essaie une opération "risquée"
  {
    printArray(Serial.list()); // Liste tous les ports disponibles
    int i = Serial.list().length; // i prend la valeur de la longueur des ports disponibles
    if (i != 0) 
    {
      String portName = Serial.list()[i-1]; 
      myPort = new Serial(this, portName, 115200); // change le baudrate comme on le souhaite
    } else 
    {
      print("Aucun Arduino n'est connecté");
      exit();
    }
  }
  catch (Exception e) // si le try ne fonctionne pas :
  { 
    print("Port COM pas disponible");
    println("Error:", e);
    exit();
  }
}*/
}
class Motif {
  private byte[] vitesses;
  private int[] pos;
  private boolean [] cibleAtteinte;

  long tInit;
  byte[] vCalc = new byte[nMoteurs];

  Motif() {
    vitesses = new byte[nMoteurs];
    pos = new int[nMoteurs];
    cibleAtteinte = new boolean[nMoteurs];
    tInit = System.nanoTime();
  }

  public void maj(int[]_pos) {
    pos = _pos;
    vitesses = calcN();
  }

  public byte[] calcN () { // calcule le nombre de pas à effectuer suivant le type de motif

    for (int i=0; i<nMoteurs; i++) {
      vCalc[i] = PApplet.parseByte(casesMot[i].getVitesse());
    }

    return vCalc;
  }

  public boolean atteindreCible(int cible, byte vit) {
    int nCiblesAtteintes = 0;
    for (int i = 0; i<nMoteurs; i++) {
      if (pos[i]==cible && cibleAtteinte[i]) {
        vCalc[i] = 0;
        nCiblesAtteintes ++;
      }

      if (!cibleAtteinte[i]) {
        if (abs(pos[i] - cible)>vit) {
          vCalc[i] = vit;
        } else {
          vCalc[i] = PApplet.parseByte(abs(pos[i] - cible));
          cibleAtteinte[i] = true;
        }
        if (pos[i] > cible) vCalc[i]*=-1;
      }
    }
    if (nCiblesAtteintes == nMoteurs) {
      cibleAtteinte = new boolean[nMoteurs];
      return true;
    } else {
      return false;
    }
  }

  public byte[] getVitesse() {
    return vitesses;
  }

  public void raz() {
    for (int i=0; i<nMoteurs; i++) {
      pos[i] = 0;
      vitesses[i] = 0;
    }
  }
}


  public void settings() { size(800, 600, P3D); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "serveurJava" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
